name: CN Client CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        node-version: [21.7.3]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install client dependencies
        working-directory: ./cn-client
        run: npm install

      - name: Build client
        working-directory: ./cn-client
        run: npm run compile
