name: CN Debugger CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        ocaml-version: [5.1.1]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Restore `_opam`
        id: cache-opam-restore
        uses: actions/cache/restore@v4
        with:
          path: _opam
          key: ${{ matrix.ocaml-version }}-debugger

      - name: Install debugger dependencies
        working-directory: ./cn-dap/debugger
        run: |
          eval $(opam env)
          opam install . --deps-only --locked -y

      - name: Cache `_opam`
        if: steps.cache-opam-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: _opam
          key: ${{ steps.cache-opam-restore.outputs.cache-primary-key }}

      - name: Build debugger
        working-directory: ./cn-dap/debugger
        run: |
          eval $(opam env)
          dune build

      - name: Run debugger tests
        working-directory: ./cn-dap/debugger
        run: |
          eval $(opam env)
          dune test
