name: CN Server CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        ocaml-version: [4.14.1]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Install server dependencies
        working-directory: ./cn-lsp/server
        run: opam install . --deps-only --locked -y

      - name: Build server
        working-directory: ./cn-lsp/server
        run: |
          eval $(opam env)
          dune build

      - name: Run server tests
        working-directory: ./cn-lsp/server
        run: |
          eval $(opam env)
          dune test
