name: CN Server CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        ocaml-version: [4.14.1]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Link lockfile
        run: ln -s cn-lsp.opam.locked-${{ matrix.ocaml-version }} cn-lsp.opam.locked

      - name: Install server dependencies
        run: opam install ./cn-lsp.opam --deps-only --locked -y

      - name: Build server
        working-directory: ./cn-lsp
        run: eval $(opam env) && dune build

      - name: Run server tests
        working-directory: ./cn-lsp
        run: eval $(opam env) && dune test
