name: Telemetry CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel in-progress job when a new push is performed
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        ocaml-version: [4.14.1, 5.1.1]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Link lockfile
        run: ln -s telemetry.opam.locked-${{ matrix.ocaml-version }} telemetry.opam.locked

      - name: Install telemetry dependencies
        run: opam install ./telemetry.opam --deps-only --locked -y

      - name: Build telemetry
        working-directory: ./telemetry
        run: eval $(opam env) && dune build

      - name: Run telemetry tests
        working-directory: ./telemetry
        run: eval $(opam env) && dune test
